
export const normailzarTexto = (text: string) => text
  .toUpperCase()
  .replace(/[ÁÀÄÂ]/g, "A")
  .replace(/[ÉÈËÊ]/g, "E")
  .replace(/[ÍÌÏÎ]/g, "I")
  .replace(/[ÓÒÖÔ]/g, "O")
  .replace(/[ÚÙÜÛ]/g, "U")
  .replace(/[áàäâ]/g, "A")
  .replace(/[éèëê]/g, "E")
  .replace(/[íìïî]/g, "I")
  .replace(/[óòöô]/g, "O")
  .replace(/[úùüû]/g, "U")
  .replace(/\*.*/g, "")
  .replace(/\?.*/g, "")
  .replace(/\(.*/g, "")
  .replace(/[,;]/g, " ")
  .replace(/\s+/g, " ")
  .trim().toLowerCase()