
export * from "./callNumber"
export * from "./libro"
export * from "./marc21"
export * from "./prestamo"
export * from "./socio"
export * from "./literaryForm"
export * from "./dewey"
export * from "./literaryGenre"
export * from "./historial"
